feat: create Products-Routes
irene2mana-T3A2-2023/SakuraPantryServer pull request #7
Opened 2023-12-04 08:13 UTC by Mana12011207

2023-12-04 11:00 UTC, ellenpham submitted a review, later dismissed
Hi Mana, I just have a few comments, there should be more to changes. I'd suggest you write an outline of all the routes as Irene was doing first before writing in code. Then we will have a meeting and discuss what routes we should keep and what not, just to align with our features.

2023-12-04 11:00 UTC, ellenpham commented on src/routes/CategoriesRoutes.js
This is definitely what I meant by creating boilerplate code for the routes. Just a few things you might need to change:

- These routes files should be in controllers folder, and should be renamed to CatogoryController, OrderController, etc. You dont need to use plural for Product, Order, Category, even with the routers, you can change them to CategoryRouter, ProductRouter, etc. 

- Make sure you have pulled the latest code in main, there should be controller folder in src folder I've already created.

2023-12-04 11:00 UTC, ellenpham commented on src/routes/CategoriesRoutes.js
> +//Update category by slug
I have not used slugs before, but have you done your reseach on how to use them. I don't think this is how you use them.  If you're not sure, we can discuss tomorrow. 

But for now, just don't worry about the slug, just create the routes as how we have learnt. 

From a quick research,

2023-12-04 11:00 UTC, ellenpham commented on src/routes/CategoriesRoutes.js
> +CategoriesRouter.put('/:slug', (req, res) => {
We should use "patch" instead of "put". Can you please change all the "put" to "patch".

2023-12-04 11:00 UTC, ellenpham commented on src/routes/OrdersRoutes.js
> +//Cancel specific order by ID
this route is not quite right, you might delete it. 

If you mean to cancel an order, it should be a PATCH method and change order status to "Cancelled"

2023-12-06 06:47 UTC, irenenguyen1017 commented
I've reviewed your PR and noticed that it fails our CI/CD checks due to some parameters being defined but not used. To resolve this, you can replace these unused parameters with an underscore (_) and push the changes again.

2023-12-07 03:09 UTC, irenenguyen1017 approved these changes

2023-12-07 03:12 UTC, ellenpham requested changes

2023-12-07 03:12 UTC, ellenpham commented on src/routes/OrderRoutes.js
> +router.get('/orders/:OrderId', OrderController.getOrderById);
can you change `OrderId` to `orderId`?

2023-12-07 03:42 UTC, ellenpham approved these changes

2023-12-07 04:25 UTC, merged